### ISSUE TITLE
Xcode linker has segmentation fault when linking due to unquoted install-name

### ISSUE THREAD

**Issue by JohnCoates** [inoahdev/tbd#6]
Xcode 9.2's ld crashes with segmentation fault 11

P.S. Love this project. Been using it for https://github.com/JohnCoatesOSS/Limitless

Issue is fixed when manually changing
`install-name:          @rpath/libapt-pkg.dylib`
to
`install-name:          '@rpath/libapt-pkg.dylib'`

**Comment by inoahdev** [comment]
BTW, can you try out the rewrite branch? 

I've been working on it for a while. Some options may not have yet been implemented (As a mistake, I'm pretty sure it's all been implemented). 

It's code is a lot cleaner and easier to interface with 👍
